#!tabledata
#{
#  "target_table"   : "#BIMC_DESCRIPTIONS",
#  "column_mappings" : {
#      "QUALIFIED_NAME" : { "type" : "constant", "value" : "WHRMIG.BASE.FIN.TRANS::AV_HB_ZCOPALIC" },
#      "LANG"           : { "type" : "function", "name" : "extractLanguageCodeFromFileName", "parameters" : {"file_name":"AV_HB_ZCOPALIC"} },
#      "ID"             : 1,
#      "DESCRIPTION"    : 2
#  }
#}
#!tabledata
# XTIT, 255
&&VIEW_NAME&&=AV_HB_ZCOPALIC
#XCOL, 120
0BILL_TYPE=Billing type
#XCOL, 120
0BILL_TYPE___T=Text column for attribute 0BILL_TYPE
#XCOL, 120
0BUS_AREA=Business area
#XCOL, 120
ZVVVOL=Warranty PEX\PAD
#XCOL, 120
0BILL_NUM=Billing document
#XCOL, 120
0BUS_AREA___T=Text column for attribute 0BUS_AREA
#XCOL, 120
0COMP_CODE=Company code
#XCOL, 120
0COMP_CODE___T=Text column for attribute 0COMP_CODE
#XCOL, 120
0CONTRACT=Number of Principal Purchase Agreement
#XCOL, 120
0COORDER=Order Number
#XCOL, 120
0COORDER___T=Text column for attribute 0COORDER
#XCOL, 120
0COSTELMNT=Cost Element
#XCOL, 120
0COSTELMNT___T=Text column for attribute 0COSTELMNT
#XCOL, 120
0CO_AREA=Controlling area
#XCOL, 120
0CO_AREA___T=Text column for attribute 0CO_AREA
#XCOL, 120
0CO_DOC_NO=CO Document Number
#XCOL, 120
0CREATEDBY=Name of person who created the object
#XCOL, 120
0CREATEDBY___T=Text column for attribute 0CREATEDBY
#XCOL, 120
0CRM_BILDAT=Billing Date
#XCOL, 120
0CURRENCY=Currency key
#XCOL, 120
0CURRENCY___T=Text column for attribute 0CURRENCY
#XCOL, 120
0CURTYPE=Currency Type
#XCOL, 120
0CURTYPE___T=Text column for attribute 0CURTYPE
#XCOL, 120
0CUSTOMER=Customer number
#XCOL, 120
0CUSTOMER___T=Text column for attribute 0CUSTOMER
#XCOL, 120
0CUST_GROUP=Customer group
#XCOL, 120
0CUST_GROUP___T=Text column for attribute 0CUST_GROUP
#XCOL, 120
0CUST_GRP1=Customer Segment Code
#XCOL, 120
0CUST_GRP1___T=Text column for attribute 0CUST_GRP1
#XCOL, 120
0CUST_GRP3=Customer group 3
#XCOL, 120
0CUST_GRP3___T=Text column for attribute 0CUST_GRP3
#XCOL, 120
0CUST_SALES=Customer number (sales view)
#XCOL, 120
0CUST_SALES__GSLSCHAN=CustSLS:Global Sales Channel
#XCOL, 120
0CUST_SALES__GSLSCHAN___T=Text column for attribute 0CUST_SALES__GSLSCHAN
#XCOL, 120
0CUST_SALES__ZACTMGRNR=CustSls: Acct Mgr Nbr
#XCOL, 120
0CUST_SALES__ZACTMGRNR___T=Text column for attribute 0CUST_SALES__ZACTMGRNR
#XCOL, 120
0CUST_SALES__ZBUYGPNR=CustSls:Buying Group Number
#XCOL, 120
0CUST_SALES__ZBUYGPNR___T=Text column for attribute 0CUST_SALES__ZBUYGPNR
#XCOL, 120
0CUST_SALES__ZCUSTHI=CustSls: Customer Hi Lvl
#XCOL, 120
0CUST_SALES__ZCUSTHI___T=Text column for attribute 0CUST_SALES__ZCUSTHI
#XCOL, 120
0CUST_SALES__ZJAMMGRNR=CustSLS: Jenn-Air Mktg Mgr
#XCOL, 120
0CUST_SALES__ZJAMMGRNR___T=Text column for attribute 0CUST_SALES__ZJAMMGRNR
#XCOL, 120
0CUST_SALES__ZPRCGP=CustSls: Price Group
#XCOL, 120
0CUST_SALES__ZPRCGP___T=Text column for attribute 0CUST_SALES__ZPRCGP
#XCOL, 120
0CUST_SALES__ZTSLSNR=CustSls: Inside Sales Rep
#XCOL, 120
0CUST_SALES__ZTSLSNR___T=Text column for attribute 0CUST_SALES__ZTSLSNR
#XCOL, 120
0CUST_SALES___T=Text column for attribute 0CUST_SALES
#XCOL, 120
0DATE=Date
#XCOL, 120
0DISTR_CHAN=Distribution Channel
#XCOL, 120
0DISTR_CHAN___T=Text column for attribute 0DISTR_CHAN
#XCOL, 120
0DIVISION=Division
#XCOL, 120
0DIVISION___T=Text column for attribute 0DIVISION
#XCOL, 120
0DOC_NUMBER=Sales document
#XCOL, 120
0DOC_NUMBER___T=Text column for attribute 0DOC_NUMBER
#XCOL, 120
0FISCPER=Fiscal year / period
#XCOL, 120
0FISCPER3=Posting period
#XCOL, 120
0FISCVARNT=Fiscal year variant
#XCOL, 120
0FISCYEAR=Fiscal year
#XCOL, 120
0FUNC_AREA=Functional area
#XCOL, 120
0FUNC_AREA___T=Text column for attribute 0FUNC_AREA
#XCOL, 120
0GI_DATE=Goods issue date
#XCOL, 120
0INCOTERMS=Incoterms part 1
#XCOL, 120
0INCOTERMS___T=Text column for attribute 0INCOTERMS
#XCOL, 120
0LOGSYS=Source System
#XCOL, 120
0MATERIAL=Material
#XCOL, 120
0MATERIAL__GPRODCD=Mtl: Global Product Code
#XCOL, 120
0MATERIAL__GPRODCD___T=Text column for attribute 0MATERIAL__GPRODCD
#XCOL, 120
0MATERIAL__GPRODCTGY=Mtl: Global Product Category
#XCOL, 120
0MATERIAL__GPRODCTGY___T=Text column for attribute 0MATERIAL__GPRODCTGY
#XCOL, 120
0MATERIAL__GPRODFAM=Mtl: Global Product Family
#XCOL, 120
0MATERIAL__GPRODFAM___T=Text column for attribute 0MATERIAL__GPRODFAM
#XCOL, 120
0MATERIAL__GPRODGRP=Mtl: Global Product Group
#XCOL, 120
0MATERIAL__GPRODGRP___T=Text column for attribute 0MATERIAL__GPRODGRP
#XCOL, 120
0MATERIAL__GPRODPLFM=Mtl: Global Product Platform
#XCOL, 120
0MATERIAL__GPRODPLFM___T=Text column for attribute 0MATERIAL__GPRODPLFM
#XCOL, 120
0MATERIAL__ZBASEMLNR=Mtl: Base Model
#XCOL, 120
0MATERIAL__ZBASEMLNR___T=Text column for attribute 0MATERIAL__ZBASEMLNR
#XCOL, 120
0MATERIAL__ZLABOR=Mtl: Energy Star
#XCOL, 120
0MATERIAL__ZLABOR___T=Text column for attribute 0MATERIAL__ZLABOR
#XCOL, 120
0MATERIAL__ZMTLCOLOR=Mtl: Color
#XCOL, 120
0MATERIAL__ZMTLCOLOR___T=Text column for attribute 0MATERIAL__ZMTLCOLOR
#XCOL, 120
0MATERIAL___T=Text column for attribute 0MATERIAL
#XCOL, 120
0MATL_GRP_1=Brand
#XCOL, 120
0MATL_GRP_1___T=Text column for attribute 0MATL_GRP_1
#XCOL, 120
0MATL_TYPE=Material type
#XCOL, 120
0MATL_TYPE___T=Text column for attribute 0MATL_TYPE
#XCOL, 120
0PART_PRCTR=Partner profit center
#XCOL, 120
0PART_PRCTR___T=Text column for attribute 0PART_PRCTR
#XCOL, 120
0PAYER=Payer
#XCOL, 120
0PAYER___T=Text column for attribute 0PAYER
#XCOL, 120
0PCOMPANY=Partner company number
#XCOL, 120
0PCOMPANY___T=Text column for attribute 0PCOMPANY
#XCOL, 120
0PLANT=Plant
#XCOL, 120
0PLANT___T=Text column for attribute 0PLANT
#XCOL, 120
0PMNTTRMS=Terms of payment key
#XCOL, 120
0PMNTTRMS___T=Text column for attribute 0PMNTTRMS
#XCOL, 120
0POST_DATE=Posting date of goods or invoice receipt
#XCOL, 120
0PRICE_DATE=Date for pricing and exchange rate
#XCOL, 120
0PROFIT_CTR=Profit Center
#XCOL, 120
0PROFIT_CTR___T=Text column for attribute 0PROFIT_CTR
#XCOL, 120
0REC_TYPE=Transaction Type
#XCOL, 120
0REC_TYPE___T=Text column for attribute 0REC_TYPE
#XCOL, 120
0REF_DOC_NO=Reference document number
#XCOL, 120
0SALESORG=Sales Organization
#XCOL, 120
0SALESORG___T=Text column for attribute 0SALESORG
#XCOL, 120
0SALES_DIST=Sales District
#XCOL, 120
0SALES_DIST___T=Text column for attribute 0SALES_DIST
#XCOL, 120
0SALES_GRP=Sales group
#XCOL, 120
0SALES_GRP___T=Text column for attribute 0SALES_GRP
#XCOL, 120
0SALES_OFF=Sales Office
#XCOL, 120
0SALES_OFF___T=Text column for attribute 0SALES_OFF
#XCOL, 120
0SHIP_TO=Ship-To Party
#XCOL, 120
0SHIP_TO___T=Text column for attribute 0SHIP_TO
#XCOL, 120
0S_ORD_ITEM=Sales document item
#XCOL, 120
0TCTTIMSTMP=UTC Time Stamp
#XCOL, 120
0UNIT=Unit of measure
#XCOL, 120
0UNIT_OF_WT=Weight unit
#XCOL, 120
0UNIT_OF_WT___T=Text column for attribute 0UNIT_OF_WT
#XCOL, 120
0UNIT___T=Text column for attribute 0UNIT
#XCOL, 120
0VALUATION=Valuation view
#XCOL, 120
0VALUATION___T=Text column for attribute 0VALUATION
#XCOL, 120
0VERSION=Version
#XCOL, 120
0VERSION___T=Text column for attribute 0VERSION
#XCOL, 120
0VOLUMEUNIT=Volume unit
#XCOL, 120
0VOLUMEUNIT___T=Text column for attribute 0VOLUMEUNIT
#XCOL, 120
0WBS_ELEMT=Work Breakdown Structure Element (WBS Element)
#XCOL, 120
0WBS_ELEMT___T=Text column for attribute 0WBS_ELEMT
#XCOL, 120
C_ARAWTYP=Reference procedure
#XCOL, 120
C_ARAWTYP___T=Text column for attribute C_ARAWTYP
#XCOL, 120
GCOPACHNG=COPA Profitability Segment Change
#XCOL, 120
GCOPACHNG___T=Text column for attribute GCOPACHNG
#XCOL, 120
GCOPAPTNR=COPA Profit. Segment Partner
#XCOL, 120
GCOPAPTNR___T=Text column for attribute GCOPAPTNR
#XCOL, 120
GCPOTYP=Customer Purchase Order Type
#XCOL, 120
GCPOTYP___T=Text column for attribute GCPOTYP
#XCOL, 120
GLNOFBUS=Global Line of Business
#XCOL, 120
GLNOFBUS___T=Text column for attribute GLNOFBUS
#XCOL, 120
GORGUNIT=Reference Organizational Unit
#XCOL, 120
GPRODCD=Global Product Code
#XCOL, 120
GPRODCD___T=Text column for attribute GPRODCD
#XCOL, 120
GPRODCTGY=Global Product Category
#XCOL, 120
GPRODCTGY___T=Text column for attribute GPRODCTGY
#XCOL, 120
GPRODFAM=Global Product Family
#XCOL, 120
GPRODFAM___T=Text column for attribute GPRODFAM
#XCOL, 120
GPRODGRP=Global Product Group
#XCOL, 120
GPRODGRP___T=Text column for attribute GPRODGRP
#XCOL, 120
GPRODPLFM=Global Product Platform
#XCOL, 120
GPRODPLFM___T=Text column for attribute GPRODPLFM
#XCOL, 120
GPRODPLNT=Producing Plant
#XCOL, 120
GPRODPLNT___T=Text column for attribute GPRODPLNT
#XCOL, 120
GSLSCHAN=Global Sales Channel
#XCOL, 120
GSLSCHAN___T=Text column for attribute GSLSCHAN
#XCOL, 120
GTPARTNER=Global Trade Partner (Customer)
#XCOL, 120
GTPARTNER___T=Text column for attribute GTPARTNER
#XCOL, 120
ZACTMGRNR=Account Manager Number
#XCOL, 120
ZACTMGRNR___T=Text column for attribute ZACTMGRNR
#XCOL, 120
ZAHAMCODE=String of AHAM codes identify
#XCOL, 120
ZAHAMCODE___T=Text column for attribute ZAHAMCODE
#XCOL, 120
ZBUYGPNR=Buying Group Number
#XCOL, 120
ZBUYGPNR___T=Text column for attribute ZBUYGPNR
#XCOL, 120
ZCANCELDO=Canceled Document (char 10)
#XCOL, 120
ZCANCELDO___T=Text column for attribute ZCANCELDO
#XCOL, 120
ZCANCELIT=Canceled Doc. Item (char 6)
#XCOL, 120
ZCANCELIT___T=Text column for attribute ZCANCELIT
#XCOL, 120
ZCCTRCTGY=Cost Center Category
#XCOL, 120
ZCCTRCTGY___T=Text column for attribute ZCCTRCTGY
#XCOL, 120
ZCOMPCURR=Transaction Currency
#XCOL, 120
ZCOMPCURR___T=Text column for attribute ZCOMPCURR
#XCOL, 120
ZCOSTOBJ=Cost Object (char 12)
#XCOL, 120
ZCOSTOBJ___T=Text column for attribute ZCOSTOBJ
#XCOL, 120
ZCPRBMLGP=Comparable Model Group Identifier
#XCOL, 120
ZCPRBMLGP___T=Text column for attribute ZCPRBMLGP
#XCOL, 120
ZCTSQTYD=CTS Quantity Delivered Code
#XCOL, 120
ZCTSQTYD___T=Text column for attribute ZCTSQTYD
#XCOL, 120
ZFCSRCCD=Demand Forecast Source Code
#XCOL, 120
ZFCSRCCD___T=Text column for attribute ZFCSRCCD
#XCOL, 120
ZFRTROUTE=Freight Route
#XCOL, 120
ZFRTROUTE___T=Text column for attribute ZFRTROUTE
#XCOL, 120
ZINNOVPR=Innovation Project
#XCOL, 120
ZINNOVPR___T=Text column for attribute ZINNOVPR
#XCOL, 120
ZITEM_NUM=Item Number (char 6)
#XCOL, 120
ZITEM_NUM___T=Text column for attribute ZITEM_NUM
#XCOL, 120
ZJAMMGRNR=Jenn-Air Marketing Manager Number
#XCOL, 120
ZJAMMGRNR___T=Text column for attribute ZJAMMGRNR
#XCOL, 120
ZLDC_MX=Local Distribution Center Number
#XCOL, 120
ZLDC_MX___T=Text column for attribute ZLDC_MX
#XCOL, 120
ZMAPIND=MAP Indicator
#XCOL, 120
ZMAPIND___T=Text column for attribute ZMAPIND
#XCOL, 120
ZMSRPIND=MSRP Indicator
#XCOL, 120
ZMSRPIND___T=Text column for attribute ZMSRPIND
#XCOL, 120
ZMTLSTSCD=Material Sales Status Code
#XCOL, 120
ZMTLSTSCD___T=Text column for attribute ZMTLSTSCD
#XCOL, 120
ZODCREADT=Order Created Date
#XCOL, 120
ZOPNLPRT=O/N Operational Part
#XCOL, 120
ZORIGIN=Origins COPA
#XCOL, 120
ZORIGIN___T=Text column for attribute ZORIGIN
#XCOL, 120
ZPERIOTO=To Period (char 7)
#XCOL, 120
ZPERIOTO___T=Text column for attribute ZPERIOTO
#XCOL, 120
ZPLANACTL=Plan / Actual Indicator (char 1)
#XCOL, 120
ZPLANACTL___T=Text column for attribute ZPLANACTL
#XCOL, 120
ZPRCGP=Price Group
#XCOL, 120
ZPRCGP___T=Text column for attribute ZPRCGP
#XCOL, 120
ZPRCSHTDE=Price Source
#XCOL, 120
ZPRCSHTDE___T=Text column for attribute ZPRCSHTDE
#XCOL, 120
ZPRCSRC=Price Source Type
#XCOL, 120
ZPRFTLOSS=Profit and Loss Group Code
#XCOL, 120
ZPRFTLOSS___T=Text column for attribute ZPRFTLOSS
#XCOL, 120
ZPRODH1=Product Main Group Code
#XCOL, 120
ZPRODH1___T=Text column for attribute ZPRODH1
#XCOL, 120
ZPRODH2=Summary Product Code
#XCOL, 120
ZPRODH2___T=Text column for attribute ZPRODH2
#XCOL, 120
ZPRODH3=Product Code
#XCOL, 120
ZPRODH3___T=Text column for attribute ZPRODH3
#XCOL, 120
ZPROFSEG=Profitability Segment ID (char 10)
#XCOL, 120
ZPROFSEGC=Profitability Seg. Changes (char 4)
#XCOL, 120
ZPROFSEGC___T=Text column for attribute ZPROFSEGC
#XCOL, 120
ZPROFSEG___T=Text column for attribute ZPROFSEG
#XCOL, 120
ZPROMMAPI=Prmo Map Indicator
#XCOL, 120
ZPROMMAPI___T=Text column for attribute ZPROMMAPI
#XCOL, 120
ZREF_ITEM=Reference Doc. Item (char 6)
#XCOL, 120
ZREF_ITEM___T=Text column for attribute ZREF_ITEM
#XCOL, 120
ZSENDBUSP=Sender Business Process (char 12)
#XCOL, 120
ZSENDBUSP___T=Text column for attribute ZSENDBUSP
#XCOL, 120
ZSENDCOST=Sender Cost Center (char 10)
#XCOL, 120
ZSENDCOST___T=Text column for attribute ZSENDCOST
#XCOL, 120
ZSHIPTORE=Ship-To Region
#XCOL, 120
ZSHIPTORE___T=Text column for attribute ZSHIPTORE
#XCOL, 120
ZSHPDOCTY=Shipment Document Type
#XCOL, 120
ZSHPDOCTY___T=Text column for attribute ZSHPDOCTY
#XCOL, 120
ZSTATE=US State (2 Char)
#XCOL, 120
ZSTATE___T=Text column for attribute ZSTATE
#XCOL, 120
ZTOWIND=Top of Waterfall Price Indicator
#XCOL, 120
ZTOWIND___T=Text column for attribute ZTOWIND
#XCOL, 120
ZTSLSNR=Inside Sales Rep
#XCOL, 120
ZTSLSNR___T=Text column for attribute ZTSLSNR
#XCOL, 120
ZUPDSTALI=Update status COPA line items
#XCOL, 120
ZUPDSTALI___T=Text column for attribute ZUPDSTALI
#XCOL, 120
ZWCPTFN=Will Call Partner Function
#XCOL, 120
ZWCPTFN___T=Text column for attribute ZWCPTFN
#XCOL, 120
ZXTNOPNR=External Owned Product Number
#XCOL, 120
M_YEAR=Posting Date: Year
#XCOL, 120
M_MONTH=Posting Date: Month
#XCOL, 120
M_QUARTER=Posting Date: Quarter
#XCOL, 120
M_CALQUARTER=Posting Date: Calendar Year/Quarter
#XCOL, 120
M_CALMONTH=Posting Date: Calendar Year/Month
#XCOL, 120
M_CALWEEK=Posting Date: Calendar Year/Week
#XCOL, 120
M_CALDAY=Posting Date: Calendar Day
#XCOL, 120
0CUST_SALES__ZBUYGPHI=CustSls: Global Product Hier Level
#XCOL, 120
0CUST_SALES__SALES_GRP=CustSls: Sales Group
#XCOL, 120
0CUST_SALES__CUST_GRP1=CustSls: Customer Segment Code
#XCOL, 120
0CUST_SALES__CUST_GROUP=CustSls: Customer Group
#XCOL, 120
0MATERIAL__GPRODHIER=Matl: Global Prod Hierarchy Level
#XCOL, 120
0MATERIAL__ZCPRBMLGP=Matl: Comparable Model Grp Identifier
#XCOL, 120
0MATERIAL__ZSNOPFMLY=Matl: S&OP Product Family
#XCOL, 120
0CUST_SALES__SALES_GRP___T=Text column for attribute 0CUST_SALES__SALES_GRP
#XCOL, 120
0CUST_SALES__CUST_GRP1___T=Text column for attribute 0CUST_SALES__CUST_GRP1___T
#XCOL, 120
0CUST_SALES__CUST_GROUP___T=Text column for attribute 0CUST_SALES__CUST_GROUP___T
#XCOL, 120
0MATERIAL__GPRODHIER___T=Text column for attribute 0MATERIAL__GPRODHIER___T
#XCOL, 120
0MATERIAL__ZCPRBMLGP___T=Text column for attribute 0MATERIAL__ZCPRBMLGP___T
#XCOL, 120
0MATERIAL__ZSNOPFMLY___T=Text column for attribute 0MATERIAL__ZSNOPFMLY___T
#XCOL, 120
0CASH_DSCNT=Cash Discounts
#XCOL, 120
0CRM_GWEIGH=Gross Weight in LB
#XCOL, 120
0EXRATE_ACC=Exchange rate for FI postings
#XCOL, 120
0VOL_REBATE=Volume Rebates
#XCOL, 120
GADVALLOW=Advertising Allowance
#XCOL, 120
GARCHARGE=Open A/R Charge
#XCOL, 120
GBRANDSGA=Brand Other SG&A
#XCOL, 120
GBRPROMO=Admin IC Expense
#XCOL, 120
GCASHBACK=Consumer Cash Backs
#XCOL, 120
GCONSPREM=Non-Cash Premiums
#XCOL, 120
GCOSCONT=COS Contingency
#XCOL, 120
GCOSTQTY=Delivery Disc/Prem
#XCOL, 120
GDIV_VAR=Div Other Mfg Var
#XCOL, 120
GDIV_VVAR=Division Volume Variance
#XCOL, 120
GENGINEER=Engineering
#XCOL, 120
GEQUIVUN=Quantity Shipped
#XCOL, 120
GFDCINFRT=OEM-Whr Purch Prod
#XCOL, 120
GFD_2_TP=Factory Direct to Trade Partner
#XCOL, 120
GFIELDADJ=Field Adjustments
#XCOL, 120
GFIXFRWR=Fixed Freight and Warehouse
#XCOL, 120
GFIXTCBUR=Fixed TC Burden
#XCOL, 120
GFIXTCDPR=Fixed TC Depr/Amort
#XCOL, 120
GFIXTCOTH=Fixed TC Other
#XCOL, 120
GFIXWARR=Warranty Other Fixed
#XCOL, 120
GFLOORPLN=Floor Planning Allow
#XCOL, 120
GFRTRECOV=Freight Recovery
#XCOL, 120
GFRTWVAR=Freight and Warehouse Variances
#XCOL, 120
GFUTUSE1=Future Use 1
#XCOL, 120
GFUTUSE2=Future Use 2
#XCOL, 120
GGMFCOND=GMF Conditional
#XCOL, 120
GGMFDISCR=GMF Discretionary
#XCOL, 120
GINFRABRD=Infra Brand
#XCOL, 120
GGMF_POS=GMF Point of Sales
#XCOL, 120
GICMARKFM=Uplift IC (FMV)
#XCOL, 120
GICMARKUP=Engineering IC Exp
#XCOL, 120
GINFRADM=Infrastructure Admin
#XCOL, 120
GINFTRADE=Infra Trade
#XCOL, 120
GINV_VAR=Inventory Variances
#XCOL, 120
GLIABEXP=Product Liability Expense
#XCOL, 120
GMEDIAADV=Media Advertising
#XCOL, 120
GMISCVAR=Div Burden Spend Var
#XCOL, 120
GOTHERCOS=Other Cost of Sales
#XCOL, 120
GPOS_LIT=RG POS/Literature
#XCOL, 120
GPPRODVAR=Purchase Product Variance
#XCOL, 120
GPROCRMNT=Procurement
#XCOL, 120
GPRODDSGN=Global Product Design
#XCOL, 120
GPUBRELNS=RG Public Relations
#XCOL, 120
GRESTRUCT=Restructuring & Other
#XCOL, 120
GREVLISTD=List Price-Discounts
#XCOL, 120
GREVLISTI=List Price - Adjust
#XCOL, 120
GREVLISTP=Revenue - List Price
#XCOL, 120
GSLS_VOL=Unit Shipments
#XCOL, 120
GSPA=Sales Pricing Allow
#XCOL, 120
GTPICOND=TPI Conditional
#XCOL, 120
GTPIDISCR=TPI Discretionary
#XCOL, 120
GTPI_POS=TPI Point of Sale
#XCOL, 120
GTRADESGA=Trade Other SG&A
#XCOL, 120
GTRADSHOW=RG Trade Shows
#XCOL, 120
GTRAILREB=Trailing Rebate Allowance
#XCOL, 120
GUNITMAJR=Unit Shipment Majors
#XCOL, 120
GVARLGCOS=Var Log Service COS
#XCOL, 120
GVARTCBUR=Var TC Burden
#XCOL, 120
GVARTCFRT=Var TC Freight-in
#XCOL, 120
GVARTCLAB=Var TC Labor
#XCOL, 120
GVARTCMAT=Var TC Material
#XCOL, 120
GVARTCMPV=Var TC MPV/VPC/PPV
#XCOL, 120
GVARTCOTH=Var TC Other
#XCOL, 120
GVARWRHSE=Secondary Whse (RDC)
#XCOL, 120
GVARWRNTY=Var Warranty
#XCOL, 120
GVAR_LDC=Secondary Frt (LDC)
#XCOL, 120
GVAR_RDC=Primary Frt(Stk Trf)
#XCOL, 120
GVOLCUBFT=Cubic Ft Volume
#XCOL, 120
GWARRCCTR=Warranty Call Center
#XCOL, 120
GWARRVAR=Warranty Variances
#XCOL, 120
G_MPV=Material Price Variance
#XCOL, 120
G_M_AND_T=M&T
#XCOL, 120
ZCLAIMEDC=Claimed Co-op
#XCOL, 120
ZEXROP_CC=Exchange rate for op.curr to co.code curr
#XCOL, 120
ZEXROP_GR=Exchange rate op.curr to gr.curr
#XCOL, 120
ZPPNMSRP=MSRP Price
#XCOL, 120
ZPPNMAP=MAP Price
#XCOL, 120
ZPPNPMAP=Promotional MAP Price
#XCOL, 120
ZRDCFRTTP=Secondary Frt (RDC)
#XCOL, 120
ZSPIFF=SPIFF Allowance
#XCOL, 120
ZTOWPRC=Top of Waterfall Price
#XCOL, 120
ZVVR10=Warehousing IC Exp
