#!tabledata
#{
#  "target_table"   : "#BIMC_DESCRIPTIONS",
#  "column_mappings" : {
#      "QUALIFIED_NAME" : { "type" : "constant", "value" : "WHRMIG.BASE.FIN.TRANS::CV_HB_ZGPSPPCH" },
#      "LANG"           : { "type" : "function", "name" : "extractLanguageCodeFromFileName", "parameters" : {"file_name":"CV_HB_ZGPSPPCH"} },
#      "ID"             : 1,
#      "DESCRIPTION"    : 2
#  }
#}
#!tabledata
# XTIT, 255
&&VIEW_NAME&&=GPS ODS for Precalculated KF Plan-Fcst 2015+
#XCOL, 120
GSLVOLPMP=GSLVOLPMP
#XCOL, 120
GPRODGRP__T=GPRODGRP__T
#XCOL, 120
0MATERIAL__T=0MATERIAL__T
#XCOL, 120
ZVERSPRI___T=ZVERSPRI___T
#XCOL, 120
ZVERSPRI=ZVERSPRI
#XCOL, 120
ZVERSCUR___T=ZVERSCUR___T
#XCOL, 120
ZVERSCUR=ZVERSCUR
#XCOL, 120
ZPRODH2=ZPRODH2
#XCOL, 120
ZPRIPERLO=ZPRIPERLO
#XCOL, 120
ZPRIPERHI=ZPRIPERHI
#XCOL, 120
ZPRFTLOSS___T=ZPRFTLOSS___T
#XCOL, 120
ZPRFTLOSS=ZPRFTLOSS
#XCOL, 120
ZCURPERLO=ZCURPERLO
#XCOL, 120
ZCURPERHI=ZCURPERHI
#XCOL, 120
ZCOMPMODL=ZCOMPMODL
#XCOL, 120
ZCHANNEL4___T=ZCHANNEL4___T
#XCOL, 120
ZCHANNEL4=ZCHANNEL4
#XCOL, 120
GPRODPLFM___T=GPRODPLFM___T
#XCOL, 120
GPRODPLFM=GPRODPLFM
#XCOL, 120
GPRODGRP=GPRODGRP
#XCOL, 120
GPRODFAM___T=GPRODFAM___T
#XCOL, 120
GPRODFAM=GPRODFAM
#XCOL, 120
GPRODCTGY=GPRODCTGY
#XCOL, 120
GPRDFMPL=GPRDFMPL
#XCOL, 120
GLNOFBUS___T=GLNOFBUS___T
#XCOL, 120
GLNOFBUS=GLNOFBUS
#XCOL, 120
GBASEMLNR=GBASEMLNR
#XCOL, 120
0VOLUMEUNIT=0VOLUMEUNIT
#XCOL, 120
0UNIT___T=0UNIT___T
#XCOL, 120
0UNIT_OF_WT=0UNIT_OF_WT
#XCOL, 120
0UNIT=0UNIT
#XCOL, 120
0SALESORG___T=0SALESORG___T
#XCOL, 120
0SALESORG=0SALESORG
#XCOL, 120
0MATL_GRP_1___T=0MATL_GRP_1___T
#XCOL, 120
0MATL_GRP_1=0MATL_GRP_1
#XCOL, 120
0MATERIAL=0MATERIAL
#XCOL, 120
0DIVISION=0DIVISION
#XCOL, 120
0DISTR_CHAN___T=0DISTR_CHAN___T
#XCOL, 120
0DISTR_CHAN=0DISTR_CHAN
#XCOL, 120
0CURRENCY___T=0CURRENCY___T
#XCOL, 120
0CURRENCY=0CURRENCY
#XCOL, 120
0CURKEY_LC___T=0CURKEY_LC___T
#XCOL, 120
0CURKEY_LC=0CURKEY_LC
#XCOL, 120
0COUNTRY___T=0COUNTRY___T
#XCOL, 120
0COUNTRY=0COUNTRY
#XCOL, 120
0COPASLQTU=0COPASLQTU
#XCOL, 120
GPRODCTGY__T=GPRODCTGY__T
#XCOL, 120
ZWARVAR_O=ZWARVAR_O
#XCOL, 120
ZWARVAR_L=ZWARVAR_L
#XCOL, 120
ZWARVAROP=ZWARVAROP
#XCOL, 120
ZWARVARLP=ZWARVARLP
#XCOL, 120
ZVWR_LP=ZVWR_LP
#XCOL, 120
ZVWR_L=ZVWR_L
#XCOL, 120
ZVWR_0P=ZVWR_0P
#XCOL, 120
ZVWR_0=ZVWR_0
#XCOL, 120
ZVWRHS_OP=ZVWRHS_OP
#XCOL, 120
ZVWRHS_O=ZVWRHS_O
#XCOL, 120
ZVWRHS_LP=ZVWRHS_LP
#XCOL, 120
ZVWRHS_L=ZVWRHS_L
#XCOL, 120
ZVOCOS_OP=ZVOCOS_OP
#XCOL, 120
ZVOCOS_O=ZVOCOS_O
#XCOL, 120
ZVOCOS_LP=ZVOCOS_LP
#XCOL, 120
ZVOCOS_L=ZVOCOS_L
#XCOL, 120
ZVFRGHT_O=ZVFRGHT_O
#XCOL, 120
ZVFRGHT_L=ZVFRGHT_L
#XCOL, 120
ZVFRGHTOP=ZVFRGHTOP
#XCOL, 120
ZVFRGHTLP=ZVFRGHTLP
#XCOL, 120
ZSLSVOLP=ZSLSVOLP
#XCOL, 120
ZSLSVOL=ZSLSVOL
#XCOL, 120
ZPFXINV=ZPFXINV
#XCOL, 120
ZPFCTC=ZPFCTC
#XCOL, 120
ZOTHVAR_O=ZOTHVAR_O
#XCOL, 120
ZOTHVAR_L=ZOTHVAR_L
#XCOL, 120
ZOTHVAROP=ZOTHVAROP
#XCOL, 120
ZOTHVARLP=ZOTHVARLP
#XCOL, 120
ZOARCHR_O=ZOARCHR_O
#XCOL, 120
ZOARCHR_L=ZOARCHR_L
#XCOL, 120
ZOARCHROP=ZOARCHROP
#XCOL, 120
ZOARCHRLP=ZOARCHRLP
#XCOL, 120
ZMRGTC=ZMRGTC
#XCOL, 120
ZMRGGS=ZMRGGS
#XCOL, 120
ZMRGALLOW=ZMRGALLOW
#XCOL, 120
ZMFGVAR_O=ZMFGVAR_O
#XCOL, 120
ZMFGVAR_L=ZMFGVAR_L
#XCOL, 120
ZMFGVAROP=ZMFGVAROP
#XCOL, 120
ZMFGVARLP=ZMFGVARLP
#XCOL, 120
ZLFLVWRO=ZLFLVWRO
#XCOL, 120
ZLFLVWRL=ZLFLVWRL
#XCOL, 120
ZLFLVWHO=ZLFLVWHO
#XCOL, 120
ZLFLVPCO=ZLFLVPCO
#XCOL, 120
ZLFLVWHL=ZLFLVWHL
#XCOL, 120
ZLFLVPCL=ZLFLVPCL
#XCOL, 120
ZLFLVFRTO=ZLFLVFRTO
#XCOL, 120
ZLFLVFRTL=ZLFLVFRTL
#XCOL, 120
ZLFLOCSGO=ZLFLOCSGO
#XCOL, 120
ZLFLOCSGL=ZLFLOCSGL
#XCOL, 120
ZLFLOARO=ZLFLOARO
#XCOL, 120
ZLFLOARL=ZLFLOARL
#XCOL, 120
ZL4LTCFCP=ZL4LTCFCP
#XCOL, 120
ZL4LTCFC=ZL4LTCFC
#XCOL, 120
ZL4LTC1=ZL4LTC1
#XCOL, 120
ZL4LTC=ZL4LTC
#XCOL, 120
ZL4LGS1=ZL4LGS1
#XCOL, 120
ZL4LGS=ZL4LGS
#XCOL, 120
ZL4LALLOW=ZL4LALLOW
#XCOL, 120
ZL4LALLO1=ZL4LALLO1
#XCOL, 120
ZGRSLS_OP=ZGRSLS_OP
#XCOL, 120
ZGRSLS_O=ZGRSLS_O
#XCOL, 120
ZGRSLS_LP=ZGRSLS_LP
#XCOL, 120
ZGRSLS_L=ZGRSLS_L
#XCOL, 120
ZFWVAR_OP=ZFWVAR_OP
#XCOL, 120
ZFWVAR_O=ZFWVAR_O
#XCOL, 120
ZFWVAR_LP=ZFWVAR_LP
#XCOL, 120
ZFWVAR_L=ZFWVAR_L
#XCOL, 120
ZCFCTC=ZCFCTC
#XCOL, 120
ZCEVOCOS=ZCEVOCOS
#XCOL, 120
ZCEVOAR=ZCEVOAR
#XCOL, 120
ZCEVAWRH=ZCEVAWRH
#XCOL, 120
ZCEVAWAR=ZCEVAWAR
#XCOL, 120
ZCEVAPC=ZCEVAPC
#XCOL, 120
ZCEVAFRT=ZCEVAFRT
#XCOL, 120
ZCETC=ZCETC
#XCOL, 120
ZCELTC=ZCELTC
#XCOL, 120
ZCEGS=ZCEGS
#XCOL, 120
ZCEALLOW=ZCEALLOW
#XCOL, 120
G_TTC_OP=G_TTC_OP
#XCOL, 120
G_TTC_OC=G_TTC_OC
#XCOL, 120
G_TTC_LP=G_TTC_LP
#XCOL, 120
G_TTC_L=G_TTC_L
#XCOL, 120
GTVTCPMOP=GTVTCPMOP
#XCOL, 120
GTVTCPMLP=GTVTCPMLP
#XCOL, 120
GTVARTC_O=GTVARTC_O
#XCOL, 120
GTVARTC_L=GTVARTC_L
#XCOL, 120
GTVARTCOP=GTVARTCOP
#XCOL, 120
GTVARTCLP=GTVARTCLP
#XCOL, 120
GTTCPM_OP=GTTCPM_OP
#XCOL, 120
GTTCPM_LP=GTTCPM_LP
#XCOL, 120
GTALLOW_O=GTALLOW_O
#XCOL, 120
GTALLOW_L=GTALLOW_L
#XCOL, 120
GTALLOWTP=GTALLOWTP
#XCOL, 120
GTALLOWOP=GTALLOWOP
#XCOL, 120
GTALLOWLP=GTALLOWLP
