#!tabledata
#{
#  "target_table"   : "#BIMC_DESCRIPTIONS",
#  "column_mappings" : {
#      "QUALIFIED_NAME" : { "type" : "constant", "value" : "WHRMIG.BUS.FIN.ISC::CV_ZPRODH2_HIER_LVL" },
#      "LANG"           : { "type" : "function", "name" : "extractLanguageCodeFromFileName", "parameters" : {"file_name":"CV_ZPRODH2_HIER_LVL"} },
#      "ID"             : 1,
#      "DESCRIPTION"    : 2
#  }
#}
#!tabledata
# XTIT, 255
&&VIEW_NAME&&=Summary Product Code (SPC) Hierarhcy - OTR UNIT GROUPINGS
#XCOL, 120
CC_SUMM_PROD_CODE=Summary Product Code Description 
#XCOL, 120
IP_HIER=Enter Hierarchy
#XCOL, 120
IP_LANGU=Enter Langue
#XCOL, 120
LVL1_TXTMD=Level 1
#XCOL, 120
LVL2_TXTMD=Level 2
#XCOL, 120
LVL3_TXTMD=Level 3
#XCOL, 120
LVL4_TXTMD=Level 4
#XCOL, 120
ZPRODH2_NODE=Summary Product Code
#XCOL, 120
ZPRODH2_TXTMD=Summary Prod. Code Text
#XCOL, 120
LVL1_NODE=Level 1 Node
#XCOL, 120
LVL2_NODE=Level 2 Node
#XCOL, 120
LVL3_NODE=Level 3 Node
#XCOL, 120
LVL4_NODE=Level 4 Node
