#!tabledata
#{
#  "target_table"   : "#BIMC_DESCRIPTIONS",
#  "column_mappings" : {
#      "QUALIFIED_NAME" : { "type" : "constant", "value" : "WHRMIG.BASE::DIM_HB_MATERIAL" },
#      "LANG"           : { "type" : "function", "name" : "extractLanguageCodeFromFileName", "parameters" : {"file_name":"DIM_HB_MATERIAL"} },
#      "ID"             : 1,
#      "DESCRIPTION"    : 2
#  }
#}
#!tabledata
# XTIT, 255
&&VIEW_NAME&&=Dimensional HANA Base Calculation View for 0MATERIAL
#XCOL, 120
0MATERIAL__0BASE_UOM=Mtl: Base Unit
#XCOL, 120
0MATERIAL__0CH_ON=Mtl: Changed on
#XCOL, 120
0MATERIAL__0CREATEDON=Mtl: Created on
#XCOL, 120
0MATERIAL__0DIVISION=Mtl: Division
#XCOL, 120
0MATERIAL__0ME_AUTHGRP=Mtl: Auth Grp
#XCOL, 120
0MATERIAL__0ME_AUTHGRP___T=Mtl: Auth Grp text
#XCOL, 120
0MATERIAL__0NET_WEIGHT=Mtl: Net weight
#XCOL, 120
0MATERIAL__0PO_UNIT=Mtl: Order unit
#XCOL, 120
0MATERIAL__0PROD_HIER=Mtl: Prod Lvl Grp code
#XCOL, 120
0MATERIAL__0PROD_HIER___T=Mtl: Prod Lvl Grp text
#XCOL, 120
0MATERIAL__0SIZE_DIM=Mtl: Size/dimension
#XCOL, 120
0MATERIAL__0STD_DESCR=Mtl: COSAC Code
#XCOL, 120
0MATERIAL__0UNIT_DIM=Mtl: Unit
#XCOL, 120
0MATERIAL__0UNIT_OF_WT=Mtl: Weight unit
#XCOL, 120
0MATERIAL__0VOLUME=Mtl: Volume
#XCOL, 120
0MATERIAL__0VOLUMEUNIT=Mtl: Volume unit
#XCOL, 120
0MATERIAL__0WIDTH=Mtl: Width
#XCOL, 120
0MATERIAL__GCOUNT=Mtl: Record Count
#XCOL, 120
0MATERIAL__GPRODCD=Mtl: Gbl Prod Code
#XCOL, 120
0MATERIAL__GPRODCD___T=Mtl: Gbl Prod Code text
#XCOL, 120
0MATERIAL__GPRODCTGY=Mtl: Gbl Prod Ctgy
#XCOL, 120
0MATERIAL__GPRODCTGY___T=Mtl: Gbl Prod Ctgy text
#XCOL, 120
0MATERIAL__GPRODFAM=Mtl: Gbl Prod Family
#XCOL, 120
0MATERIAL__GPRODFAM___T=Mtl: Gbl Prod Family text
#XCOL, 120
0MATERIAL__GPRODGRP=Mtl: Gbl Prod Group
#XCOL, 120
0MATERIAL__GPRODGRP___T=Mtl: Gbl Prod Group text
#XCOL, 120
0MATERIAL__GPRODHIER=Mtl: Gbl Prod Hier Lvl
#XCOL, 120
0MATERIAL__GPRODHIER___T=Mtl: Gbl Prod Hier Lvl text
#XCOL, 120
0MATERIAL__GPRODPLFM=Mtl: Gbl Prod Plfm
#XCOL, 120
0MATERIAL__GPRODPLFM___T=Mtl: Gbl Prod Plfm text
#XCOL, 120
0MATERIAL__ZAHAMFEGP=Mtl: AHAM Code
#XCOL, 120
0MATERIAL__ZAHAMFEGP___T=Mtl: AHAM Code text
#XCOL, 120
0MATERIAL__ZBASEMLNR=Mtl: Base Model
#XCOL, 120
0MATERIAL__ZBASEMLNR___T=Mtl: Base Model text
#XCOL, 120
0MATERIAL__ZCMPSTSCD=Mtl: SAP Matl View Maint
#XCOL, 120
0MATERIAL__ZCNFPRC=Mtl: Confined Pricing Status
#XCOL, 120
0MATERIAL__ZCPRBMLGP=Mtl: Cmprbl Model
#XCOL, 120
0MATERIAL__ZHZMTLNR=Mtl: Hazardous Matl Nbr
#XCOL, 120
0MATERIAL__ZINNOVCD=Mtl:  Innov Code
#XCOL, 120
0MATERIAL__ZINNOVCD___T=Mtl:  Innov Code text
#XCOL, 120
0MATERIAL__ZINNOVPR=Mtl: Innov Proj
#XCOL, 120
0MATERIAL__ZINNOVPR___T=Mtl: Innov Proj text
#XCOL, 120
0MATERIAL__ZITMCTGCD=Mtl: Item Catgy Code
#XCOL, 120
0MATERIAL__ZITMCTGCD___T=Mtl: Item Catgy text
#XCOL, 120
0MATERIAL__ZLAPRDNDT=Mtl: Last Prodn Date
#XCOL, 120
0MATERIAL__ZMPCCD=Mtl: MPC Code
#XCOL, 120
0MATERIAL__ZMPCCD___T=Mtl: MPC Code text
#XCOL, 120
0MATERIAL__ZMNTSTSCD=Mtl: SAP Matl Mnt Dept Cd
#XCOL, 120
0MATERIAL__ZMTLCOLOR=Mtl: Color code
#XCOL, 120
0MATERIAL__ZMTLCOLOR___T=Mtl: Color text
#XCOL, 120
0MATERIAL__ZOLDMTLNR=Mtl: Old Material Nbr
#XCOL, 120
0MATERIAL__ZPRDPLNGP=Mtl: Prdn Plng Grp
#XCOL, 120
0MATERIAL__ZPRDPLNGP___T=Mtl: Prdn Plng Grp text
#XCOL, 120
0MATERIAL__ZPRODH1=Mtl: Prod Main Grp
#XCOL, 120
0MATERIAL__ZPRODH1___T=Mtl: Prod Main Grp text
#XCOL, 120
0MATERIAL__ZPRODH2=Mtl: Smry Prod Code
#XCOL, 120
0MATERIAL__ZPRODH2___T=Mtl: Smry Prod Code text
#XCOL, 120
0MATERIAL__ZPRODH3=Mtl: Product Code
#XCOL, 120
0MATERIAL__ZPRODH3___T=Mtl: Product Code text
#XCOL, 120
0MATERIAL__ZPRTPKGCD=Mtl: Part Pkg Matl Code
#XCOL, 120
0MATERIAL__ZPRTPKGCD___T=Mtl: Part Pkg Matl Code text
#XCOL, 120
0MATERIAL__ZSNOPFMLY=Mtl: S&OP Product Family
#XCOL, 120
0MATERIAL__ZSNOPFMLY___T=Mtl: S&OP Product Family text
#XCOL, 120
0MATERIAL__ZSTKPOLCY=Mtl: Stocking Policy
#XCOL, 120
0MATERIAL__ZSTKPOLCY___T=Mtl: Stocking Policy text
#XCOL, 120
0MATERIAL__ZTPGPCD=Mtl: Trnspn Grp
#XCOL, 120
0MATERIAL__ZTPGPCD___T=Mtl: Trnspn Grp text
#XCOL, 120
0MATERIAL__ZTRNCODE=Mtl: Transition Code
#XCOL, 120
0MATERIAL__ZTRNCODE___T=Mtl: Transition Code text
#XCOL, 120
0MATERIAL__0CREATEDON_CC=Mtl: Created on
#XCOL, 120
0MATERIAL__0MATERIAL=Mtl: Material
#XCOL, 120
0MATERIAL__0MATERIAL___T=Mtl: Material text
#XCOL, 120
0MATERIAL__0DIVISION___T=Mtl: Diviison text
#XCOL, 120
0MATERIAL__0GROSS_WT=Mtl: Gross weight
#XCOL, 120
0MATERIAL__0EANUPC=Mtl: EAN/UPC(Material)
#XCOL, 120
0MATERIAL__0HEIGHT=Mtl: Height
#XCOL, 120
0MATERIAL__0IND_SECTOR=Mtl: Industry Sector
#XCOL, 120
0MATERIAL__0IND_SECTOR___T=Mtl: Industry Sector text
#XCOL, 120
0MATERIAL__0LENGHT=Mtl: Length
#XCOL, 120
0MATERIAL__0MATL_GROUP=Mtl: Material Group
#XCOL, 120
0MATERIAL__0MATL_GROUP___T=Mtl: Material Group text
#XCOL, 120
0MATERIAL__0MATL_TYPE=Mtl: Material Type
#XCOL, 120
0MATERIAL__0MATL_TYPE___T=Mtl: Material Type text
#XCOL, 120
0MATERIAL__0CH_ON_CC=Mtl: Changed on
