#!tabledata
#{
#  "target_table"   : "#BIMC_DESCRIPTIONS",
#  "column_mappings" : {
#      "QUALIFIED_NAME" : { "type" : "constant", "value" : "WHRMIG.BASE::DIM_HB_CUST_SALES" },
#      "LANG"           : { "type" : "function", "name" : "extractLanguageCodeFromFileName", "parameters" : {"file_name":"DIM_HB_CUST_SALES"} },
#      "ID"             : 1,
#      "DESCRIPTION"    : 2
#  }
#}
#!tabledata
# XTIT, 255
&&VIEW_NAME&&=Dimension HANA Base Calculated View for 0CUST_SALES
#XCOL, 120
0CUST_SALES__0CREATEDON_CC=CustSls: Created on
#XCOL, 120
0CUST_SALES__0CUST_SALES___T=CustSls: Customer (sales) text
#XCOL, 120
0CUST_SALES__0DIVISION=CustSls: Division
#XCOL, 120
0CUST_SALES__0CUST_SALES=CustSls: Customer (sales)
#XCOL, 120
0CUST_SALES__0CUST_SALES___TXTMD=CustSls: Customer (sales) med text
#XCOL, 120
0CUST_SALES__0DIVISION___T=CustSls: Division text
#XCOL, 120
0CUST_SALES__0DIVISION___TXTSH=CustSls: Division short text
#XCOL, 120
0CUST_SALES__0DISTR_CHAN=CustSls: Distribution Channel
#XCOL, 120
0CUST_SALES__0DISTR_CHAN___T=CustSls: Distribution Channel text
#XCOL, 120
0CUST_SALES__0DISTR_CHAN___TXTSH=CustSls: Distribution Channel short text
#XCOL, 120
0CUST_SALES__0SALESORG=CustSls: Sales Organization
#XCOL, 120
0CUST_SALES__0SALESORG___T=CustSls: Sales Organization text
#XCOL, 120
0CUST_SALES__0SALESORG___TXTLG=CustSls: Sales Organization long text
#XCOL, 120
0CUST_SALES__0ACCNT_ASGN=CustSls: Acct Asgn
#XCOL, 120
0CUST_SALES__0ACCNT_ASGN___T=CustSls: Acct Asgn text
#XCOL, 120
0CUST_SALES__0ACCNT_ASGN___TXTSH=CustSls: Acct Asgn short text
#XCOL, 120
0CUST_SALES__0COMPL_DEL=CustSls: Delvry Compl Indicator
#XCOL, 120
0CUST_SALES__0CREATEDON=CustSls: Created on
#XCOL, 120
0CUST_SALES__0CUST_GROUP=CustSls: Customer group
#XCOL, 120
0CUST_SALES__0CUST_GROUP___T=CustSls: Customer group text
#XCOL, 120
0CUST_SALES__0CUST_GROUP___TXTSH=CustSls: Customer group short text
#XCOL, 120
0CUST_SALES__0CUST_GRP1=CustSls: Customer Segment Code
#XCOL, 120
0CUST_SALES__0CUST_GRP1___T=CustSls: Customer Segment Code text
#XCOL, 120
0CUST_SALES__0CUST_GRP1___TXTSH=CustSls: Customer Segment Code short text
#XCOL, 120
0CUST_SALES__0CUST_GRP2=CustSls: CustPrcGrpOverrideCd
#XCOL, 120
0CUST_SALES__0CUST_GRP2___T=CustSls: CustPrcGrpOverrideCd text
#XCOL, 120
0CUST_SALES__0CUST_GRP2___TXTSH=CustSls: CustPrcGrpOverrideCd short text
#XCOL, 120
0CUST_SALES__0CUST_GRP4=CustSls: APO TP Grp
#XCOL, 120
0CUST_SALES__0CUST_GRP4___T=CustSls: APO TP Grp text
#XCOL, 120
0CUST_SALES__0CUST_GRP4___TXTSH=CustSls: APO TP Grp short text
#XCOL, 120
0CUST_SALES__0CUST_GRP5=CustSls: APO Dmd Fcst
#XCOL, 120
0CUST_SALES__0CUST_GRP5___T=CustSls: APO Dmd Fcst text
#XCOL, 120
0CUST_SALES__0CUST_GRP5___TXTSH=CustSls: APO Dmd Fcst short text
#XCOL, 120
0CUST_SALES__0INCOTERMS=CustSls: Incoterms
#XCOL, 120
0CUST_SALES__0INCOTERMS___T=CustSls: Incoterms text
#XCOL, 120
0CUST_SALES__0INCOTERMS2=CustSls: Incoterms 2
#XCOL, 120
0CUST_SALES__0ORDER_COMB=CustSls: ID:Order Combination
#XCOL, 120
0CUST_SALES__0INCOTERMS___TXTMD=CustSls: Incoterms med text
#XCOL, 120
0CUST_SALES__0ORDER_PROB=CustSls: Order probability
#XCOL, 120
0CUST_SALES__0PAYER=CustSls: Payer
#XCOL, 120
0CUST_SALES__0PAYER___T=CustSls: Payer text
#XCOL, 120
0CUST_SALES__0PAYER___TXTMD=CustSls: Payer med text
#XCOL, 120
0CUST_SALES__0PLANT=CustSls: Plant
#XCOL, 120
0CUST_SALES__0PLANT___T=CustSls: Plant text
#XCOL, 120
0CUST_SALES__0PLANT___TXTMD=CustSls: Plant med text
#XCOL, 120
0CUST_SALES__0PMNTTRMS=CustSls: Payment terms
#XCOL, 120
0CUST_SALES__0PMNTTRMS___T=CustSls: Payment terms text
#XCOL, 120
0CUST_SALES__0PMNTTRMS___TXTMD=CustSls: Payment terms med text
#XCOL, 120
0CUST_SALES__0SALES_DIST=CustSls: Sales district
#XCOL, 120
0CUST_SALES__0SALES_DIST___T=CustSls: Sales district text
#XCOL, 120
0CUST_SALES__0SALES_DIST___TXTSH=CustSls: Sales district short text
#XCOL, 120
0CUST_SALES__0SALES_GRP=CustSls: Sales group
#XCOL, 120
0CUST_SALES__0SALES_GRP___T=CustSls: Sales group text
#XCOL, 120
0CUST_SALES__0SALES_OFF=CustSls: Sales office
#XCOL, 120
0CUST_SALES__0SALES_GRP___TXTSH=CustSls: Sales group short text
#XCOL, 120
0CUST_SALES__0SALES_OFF___T=CustSls: Sales office text
#XCOL, 120
0CUST_SALES__0SALES_OFF___TXTSH=CustSls: Sales office short text
#XCOL, 120
0CUST_SALES__0SHIP_COND=CustSls: Shipping conditions
#XCOL, 120
0CUST_SALES__0SHIP_COND___T=CustSls: Shipping conditions text
#XCOL, 120
0CUST_SALES__0SHIP_COND___TXTSH=CustSls: Shipping conditions short text
#XCOL, 120
0CUST_SALES__GSLSCHAN=CustSls: Gbl Sls Chan
#XCOL, 120
0CUST_SALES__GSLSCHAN___T=CustSls: Gbl Sls Chan text
#XCOL, 120
0CUST_SALES__GSLSCHAN___TXTSH=CustSls: Gbl Sls Chan short text
#XCOL, 120
0CUST_SALES__ZACTMGRNR=CustSls: Acct Mgr Nbr
#XCOL, 120
0CUST_SALES__ZACTMGRNR___T=CustSls: Acct Mgr Nbr text
#XCOL, 120
0CUST_SALES__ZACTMGRNR___TXTMD=CustSls: Acct Mgr Nbr med text
#XCOL, 120
0CUST_SALES__ZBUYGPCH=CustSls: Buy Gp Chp
#XCOL, 120
0CUST_SALES__ZBUYGPCH___T=CustSls: Buy Gp Chp text
#XCOL, 120
0CUST_SALES__ZBUYGPCH___TXTMD=CustSls: Buy Gp Chp med text
#XCOL, 120
0CUST_SALES__ZBUYGPCH2=CustSls: Buy Gp Chp2
#XCOL, 120
0CUST_SALES__ZBUYGPCH2___T=CustSls: Buy Gp Chp2 text
#XCOL, 120
0CUST_SALES__ZBUYGPCH2___TXTMD=CustSls: Buy Gp Chp2 med text
#XCOL, 120
0CUST_SALES__ZBUYGPHI=CustSls: Buy Gp High Lvl Nbr
#XCOL, 120
0CUST_SALES__ZBUYGPHI___T=CustSls: Buy Gp High Lvl Nbr text
#XCOL, 120
0CUST_SALES__ZBUYGPHI___TXTMD=CustSls: Buy Gp High Lvl Nbr med text
#XCOL, 120
0CUST_SALES__ZBUYGPMS=CustSls: Buy Gp Mstr
#XCOL, 120
0CUST_SALES__ZBUYGPMS___T=CustSls: Buy Gp Mstr text
#XCOL, 120
0CUST_SALES__ZBUYGPMS___TXTMD=CustSls: Buy Gp Mstr med text
#XCOL, 120
0CUST_SALES__ZBUYGPNR___T=CustSls: Buy Gp Nbr text
#XCOL, 120
0CUST_SALES__ZBUYGPNR=CustSls: Buy Gp Nbr
#XCOL, 120
0CUST_SALES__ZBUYGPNR___TXTMD=CustSls: Buy Gp Nbr med text
#XCOL, 120
0CUST_SALES__ZCOACTNR=CustSls: Company (WHR) Acct Nbr
#XCOL, 120
0CUST_SALES__ZCRCYCD=CustSls: Currency
#XCOL, 120
0CUST_SALES__ZCUSTHI=CustSls: Cust Hi Lvl
#XCOL, 120
0CUST_SALES__ZCUSTHI___T=CustSls: Cust Hi Lvl text
#XCOL, 120
0CUST_SALES__ZCUSTHI___TXTMD=CustSls: Cust Hi Lvl med text
#XCOL, 120
0CUST_SALES__ZCUSTLVL1___T=Custsls: Payout Lvl 1 text
#XCOL, 120
0CUST_SALES__ZCUSTLVL1=Custsls: Payout Lvl 1
#XCOL, 120
0CUST_SALES__ZCUSTLVL1___TXTMD=Custsls: Payout Lvl 1 med text
#XCOL, 120
0CUST_SALES__ZCUSTLVL2=CustSls: Payout Lvl 2
#XCOL, 120
0CUST_SALES__ZCUSTLVL2___T=CustSls: Payout Lvl 2 text
#XCOL, 120
0CUST_SALES__ZCUSTLVL2___TXTMD=CustSls: Payout Lvl 2 med text
#XCOL, 120
0CUST_SALES__ZCUSTLVL3=CustSls: Payout Lvl 3
#XCOL, 120
0CUST_SALES__ZCUSTLVL3___T=CustSls: Payout Lvl 3 text
#XCOL, 120
0CUST_SALES__ZCUSTLVL3___TXTMD=CustSls: Payout Lvl 3 med text
#XCOL, 120
0CUST_SALES__ZDLVBLCK=CustSls: Delivery Block
#XCOL, 120
0CUST_SALES__ZDLVBLCK___T=CustSls: Delivery Block text
#XCOL, 120
0CUST_SALES__ZDLVBLCK___TXTSH=CustSls: Delivery Block short text
#XCOL, 120
0CUST_SALES__ZITEMPRTL=CustSls: Item Partial Dlv
#XCOL, 120
0CUST_SALES__ZITEMPRTL___T=CustSls: Item Partial Dlv text
#XCOL, 120
0CUST_SALES__ZITEMPRTL___TXTLG=CustSls: Item Partial Dlv long text
#XCOL, 120
0CUST_SALES__ZITEMPRTL___TXTMD=CustSls: Item Partial Dlv med text
#XCOL, 120
0CUST_SALES__ZITEMPRTL___TXTSH=CustSls: Item Partial Dlv short text
#XCOL, 120
0CUST_SALES__ZJAMMGRNR=CustSls: Jenn-Air Mkt Mgr
#XCOL, 120
0CUST_SALES__ZJAMMGRNR___T=CustSls: Jenn-Air Mkt Mgr text
#XCOL, 120
0CUST_SALES__ZJAMMGRNR___TXTMD=CustSls: Jenn-Air Mkt Mgr med text
#XCOL, 120
0CUST_SALES__ZMYGCUST=CustSls: Maytag Customer
#XCOL, 120
0CUST_SALES__ZODBLCKCD=CustSls: Cust Order Block Cd
#XCOL, 120
0CUST_SALES__ZODBLCKCD___T=CustSls: Cust Order Block Cd text
#XCOL, 120
0CUST_SALES__ZODBLCKCD___TXTSH=CustSls: Cust Order Block Cd short text
#XCOL, 120
0CUST_SALES__ZPRCGP=CustSls: Price Group
#XCOL, 120
0CUST_SALES__ZPRCGP___T=CustSls: Price Group text
#XCOL, 120
0CUST_SALES__ZPRCGP___TXTSH=CustSls: Price Group short text
#XCOL, 120
0CUST_SALES__ZPRCPROC=CustSls: Pricing Procedure
#XCOL, 120
0CUST_SALES__ZPRCPROC___TXTSH=CustSls: Pricing Procedure short text
#XCOL, 120
0CUST_SALES__ZPRTLDLV=CustSls: Nbr of Prtl Dlv Allowed
#XCOL, 120
0CUST_SALES__ZPRCPROC___T=CustSls: Pricing Procedure text
#XCOL, 120
0CUST_SALES__ZSTTSGP_CustSl=CustSls: Stats Group
#XCOL, 120
0CUST_SALES__ZSTTSGP___T=CustSls: Stats Group text
#XCOL, 120
0CUST_SALES__ZSTTSGP___TXTSH=CustSls: Stats Group short text
#XCOL, 120
0CUST_SALES__ZTSLSNR___T=CustSls: Inside Sales Rep text
#XCOL, 120
0CUST_SALES__ZTSLSNR=CustSls: Inside Sales Rep
#XCOL, 120
0CUST_SALES__ZTSLSNR___TXTMD=CustSls: Inside Sales Rep med text
