#!tabledata
#{
#  "target_table"   : "#BIMC_DESCRIPTIONS",
#  "column_mappings" : {
#      "QUALIFIED_NAME" : { "type" : "constant", "value" : "WHRMIG.BASE::DIM_HB_MAT_PLANT_CVTD" },
#      "LANG"           : { "type" : "function", "name" : "extractLanguageCodeFromFileName", "parameters" : {"file_name":"DIM_HB_MAT_PLANT_CVTD"} },
#      "ID"             : 1,
#      "DESCRIPTION"    : 2
#  }
#}
#!tabledata
# XTIT, 255
&&VIEW_NAME&&=AT_HB_MAT_PLANT
#XCOL, 120
0MAT_PLANT_DEL_FLAG=MtlP: Del Flag
#XCOL, 120
0MAT_PLANT__0PLANT=MtlP: Plant
#XCOL, 120
0MAT_PLANT__0PLANT___T=MtlP: Plant text
#XCOL, 120
0MAT_PLANT__0MAT_PLANT=MtlP: Material Plant
#XCOL, 120
0MAT_PLANT__0MAT_PLANT___T=MtlP: Material Plant text
#XCOL, 120
0MAT_PLANT__0ABCKEY=MtlP: ABC indicator
#XCOL, 120
0MAT_PLANT__0ABCKEY___T=MtlP: ABC indicator text
#XCOL, 120
0MAT_PLANT__0COUNTRY=MtlP: Country
#XCOL, 120
0MAT_PLANT__0BASE_UOM=MtlP: Base Unit
#XCOL, 120
0MAT_PLANT__0COUNTRY___T=MtlP: Country text
#XCOL, 120
0MAT_PLANT__0CO_AREA=MtlP: Control Area
#XCOL, 120
0MAT_PLANT__0CO_AREA___T=MtlP: Control Area text
#XCOL, 120
0MAT_PLANT__0DISMM=MtlP: MRP Type
#XCOL, 120
0MAT_PLANT__0DISMM___T=MtlP: MRP Type text
#XCOL, 120
0MAT_PLANT__0GR_PR_TIME=MtlP: GR processing time
#XCOL, 120
0MAT_PLANT__0INHSEPRODT=MtlP: InhseProdTime
#XCOL, 120
0MAT_PLANT__0MRP_CONTRL=MtlP: MRP controller
#XCOL, 120
0MAT_PLANT__0MRP_CONTRL___T=MtlP: MRP controller text
#XCOL, 120
0MAT_PLANT__0PLND_DELRY=MtlP: Planned deliv. time
#XCOL, 120
0MAT_PLANT__0PRODSCHED=MtlP: Prodn Scheduler
#XCOL, 120
0MAT_PLANT__0PROFIT_CTR=MtlP: Profit Center
#XCOL, 120
0MAT_PLANT__0PROFIT_CTR___T=MtlP: Profit Center text
#XCOL, 120
0MAT_PLANT__0PUR_GROUP=MtlP: Purchasing grp
#XCOL, 120
0MAT_PLANT__0PUR_GROUP___T=MtlP: Purchasing grp text
#XCOL, 120
0MAT_PLANT__0REPLENTIME=MtlP: Total RL time
#XCOL, 120
0MAT_PLANT__0STGE_PD_UN=MtlP: Time Unit
#XCOL, 120
0MAT_PLANT__ZAVLCKGP=MtlP: Avail Check Grp Code
#XCOL, 120
0MAT_PLANT__ZAVLCKGP___T=MtlP: Avail Check Grp text
#XCOL, 120
0MAT_PLANT__ZBCHMGTIR=MtlP: Batch Mgmt Indr
#XCOL, 120
0MAT_PLANT__ZBSTMI=MtlP: Minimum Lot Size
#XCOL, 120
0MAT_PLANT__ZBSTRF=MtlP: Rounding value (PO)
#XCOL, 120
0MAT_PLANT__ZCNRYOGCD=MtlP: Cntry of Orig
#XCOL, 120
0MAT_PLANT__ZCNRYOGCD___T=MtlP: Cntry of Orig text
#XCOL, 120
0MAT_PLANT__ZCRITPRT=MtlP: Crit Part Indr
#XCOL, 120
0MAT_PLANT__ZCULDCD=MtlP: Cust Load Code
#XCOL, 120
0MAT_PLANT__ZCULDCD___T=MtlP: Cust Load Code text
#XCOL, 120
0MAT_PLANT__ZEISBE=MtlP: Safety Stock
#XCOL, 120
0MAT_PLANT__ZEXPGPCD=MtlP: Exp/Import Grp Code
#XCOL, 120
0MAT_PLANT__ZEXPGPCD___T=MtlP: Exp/Import Grp Code text
#XCOL, 120
0MAT_PLANT__ZFAMILY=MtlP: Family Code
#XCOL, 120
0MAT_PLANT__ZFAMILY___T=MtlP: Family Code text
#XCOL, 120
0MAT_PLANT__ZFAMLYGRP=MtlP: Family Group
#XCOL, 120
0MAT_PLANT__ZFAMLYGRP___T=MtlP: Family Group text
#XCOL, 120
0MAT_PLANT__ZFCVALPRD=MtlP: Fcst Value Period
#XCOL, 120
0MAT_PLANT__ZFXHOR=MtlP: Planning time fence
#XCOL, 120
0MAT_PLANT__ZINVDPLIR=MtlP: Deployment Indr
#XCOL, 120
0MAT_PLANT__ZLOTSZ=MtlP: Lot Size
#XCOL, 120
0MAT_PLANT__ZLOTSZ___T=MtlP: Lot Size text
#XCOL, 120
0MAT_PLANT__ZMDV01=MtlP: Assembly Line Number
#XCOL, 120
0MAT_PLANT__ZMFGPLT=MtlP: Mfg Plant
#XCOL, 120
0MAT_PLANT__ZMFGPLT___T=MtlP: Mfg Plant text
#XCOL, 120
0MAT_PLANT__ZMNTSTSCD=MtlP: Matl Mnt Dept
#XCOL, 120
0MAT_PLANT__ZMRPMIXCD=MtlP: MRP Mixed Assy
#XCOL, 120
0MAT_PLANT__ZMRP_CTRL=MtlP: MRP Ctrl w/o Plant
#XCOL, 120
0MAT_PLANT__ZMRP_CTRL___T=MtlP: MRP Ctrl w/o Plant text
#XCOL, 120
0MAT_PLANT__ZMTLFRTGP=MtlP: Matl Frt Grp Cd
#XCOL, 120
0MAT_PLANT__ZMTLFRTGP___T=MtlP: Matl Frt Grp Cd text
#XCOL, 120
0MAT_PLANT__ZMTLVALCG=MtlP: Matl Val Catgy
#XCOL, 120
0MAT_PLANT__ZMTLVALCG___T=MtlP: Matl Val Catgy text
#XCOL, 120
0MAT_PLANT__ZNEGALWIR=MtlP: BOH Neg Qty Allow Indr
#XCOL, 120
0MAT_PLANT__ZPLNGGPIR=MtlP: Plnng Rqmt Grp
#XCOL, 120
0MAT_PLANT__ZPLTSTSCD=MtlP: Matl Plt Status Code
#XCOL, 120
0MAT_PLANT__ZPLTSTSCD___T=MtlP: Matl Plt Status Code text
#XCOL, 120
0MAT_PLANT__ZPLTSTSDT=MtlP: Matl Plt Stat Efct
#XCOL, 120
0MAT_PLANT__ZPOAUTOIR=MtlP: PO Auto Allow Indr
#XCOL, 120
0MAT_PLANT__ZPRCRTYP=MtlP: Prcr Type Code
#XCOL, 120
0MAT_PLANT__ZPRSTLCNR=MtlP: Prcr Strg Locn
#XCOL, 120
0MAT_PLANT__ZPRSTLCNR___T=MtlP: Prcr Strg Locn text
#XCOL, 120
0MAT_PLANT__ZRCINSPIR=MtlP: Rcvg Insp Indr
#XCOL, 120
0MAT_PLANT__ZRQMTTYP=MtlP: PrtRqmtSrcType
#XCOL, 120
0MAT_PLANT__ZSERNRPFL=MtlP: Serial Nbr Profile Cd
#XCOL, 120
0MAT_PLANT__ZSERNRPFL___T=MtlP: Serial Nbr Profile Cd text
#XCOL, 120
0MAT_PLANT__ZSHZET=MtlP: Safety time (days)
#XCOL, 120
0MAT_PLANT__ZSPLPRCST=MtlP: Spl Procure Type Cst
#XCOL, 120
0MAT_PLANT__ZSPLPRCST___T=MtlP: Spl Procure Type Cst text
#XCOL, 120
0MAT_PLANT__ZSPLPRTYP=MtlP: Spl ProcureType
#XCOL, 120
0MAT_PLANT__ZSPLPRTYP___T=MtlP: Spl ProcureType text
#XCOL, 120
0MAT_PLANT__ZSTATECD=MtlP: SAP State Code
#XCOL, 120
0MAT_PLANT__ZSTATECD___T=MtlP: SAP State Code text
#XCOL, 120
0MAT_PLANT__ZSTLCNR=MtlP: SAP Storg Locn
#XCOL, 120
0MAT_PLANT__ZSVCLVL=MtlP: Matl Service Lvl
#XCOL, 120
0MAT_PLANT__ZSVCLVL___T=MtlP: Matl Service Lvl text
#XCOL, 120
0MAT_PLANT__ZTRFFCLSS=MtlP: Tariff Clss Cd
#XCOL, 120
0MAT_PLANT__ZTRFFCLSS___T=MtlP: Tariff Clss Cd text
